### PR TITLE
v4 proposal

### PR DESCRIPTION
**Pull request by davidmarkclements**
first pass , as per #15

### CODE REVIEW

**Comment by davidmarkclements** [comment]
Along with API changes, there's quite a few fixes - also changed behaviour of value, 
so that it's essentially the default if no input is supplied

still todo 

- readme
- there are issues with delete and insertion (seem to be preexisting)

**Comment by 0x00A** [comment]
LGTM! Any steps to reproduce on deletes and inserts?

**Comment by davidmarkclements** [comment]
so run test.js and then try to backspace, also inserts work it's just the
cursor that's not positioned correctly (because we write out whole strings)
- so I'm just looking at using save and restore cursor position (\u001b[s
and \u001b[u)

also - I have the readme (and jsdocs) written, haven't pushed yet

On Sun, Feb 28, 2016 at 11:54 PM, paolo fragomeni <notifications@github.com>
wrote:

> LGTM! Any steps to reproduce on deletes and inserts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0x00A/prompt-sync/pull/16#issuecomment-189972578>.
>



-- 
David Mark Clements Ltd is a company registered in Northern Ireland.
Registered number: NI617728. Registered office: Unit 22a, Pennybridge
Industrial Estate,
Ballymena, Antrim, BT42 3HB

**Comment by 0x00A** [comment]
save and restore would probably work perfectly!

**Comment by davidmarkclements** [comment]
ok updated - did a commit amend and force push to keep commits shallow

@0x00A would you mind giving it a check over and publish if you're happy 

time for :sleeping: for me :zzz:

**Comment by davidmarkclements** [comment]
oh hold on, wait one sec, need to publish history module

**Comment by davidmarkclements** [comment]
ok done, https://www.npmjs.com/package/prompt-sync-history 

PR is ready for inspection

**Comment by 0x00A** [comment]
LGTM!

**Pull request merged**
